"""Backend interface for Presonus device control."""

from __future__ import annotations

from typing import Any, Protocol


class DeviceBackend(Protocol):
    """Protocol for high-level device control backends."""

    mode: str

    def query_state(self) -> Any: ...
    def get_device_info(self) -> Any: ...
    def set_channel_gain(self, channel_id: int, gain: float) -> bool: ...
    def set_channel_volume(self, channel_id: int, volume: float) -> bool: ...
    def set_channel_pan(self, channel_id: int, pan: int) -> bool: ...
    def set_channel_mute(self, channel_id: int, muted: bool) -> bool: ...
    def set_channel_solo(self, channel_id: int, solo: bool) -> bool: ...
    def set_channel_phase(self, channel_id: int, phase_inv: bool) -> bool: ...
    def set_channel_input_source(self, channel_id: int, source: str) -> bool: ...
    def set_headphones_source(self, *args: Any) -> bool: ...
    def set_master_volume(self, volume: float) -> bool: ...
    def set_monitor_blend(self, blend: int) -> bool: ...
    def set_headphones_volume(self, volume: float) -> bool: ...
    def set_compressor(self, channel_id: int, settings: Any) -> bool: ...
    def set_gate(self, channel_id: int, settings: Any) -> bool: ...
    def set_eq(self, channel_id: int, eq: Any) -> bool: ...
    def set_limiter(self, channel_id: int, limiter: Any) -> bool: ...
    def set_channel_preset(self, channel_id: int, preset: Any) -> bool: ...
    def set_routing(self, channel_id: int, output: Any, volume: int, routed: bool, solo: bool) -> bool: ...
    def set_aux_send_level(self, channel_id: int, aux_id: int, level: int) -> bool: ...
    def set_reverb_send_level(self, channel_id: int, level: int) -> bool: ...
